version: "3"

services:
  backend:
    build: ./backend
    command:
      - /bin/bash 
      - '-c' 
      - "python manage.py migrate && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/usr/src/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend/:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    ports:
      - "8080:8080"
    depends_on: 
      - backend
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgresql_dev/data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
      