# Generated by Django 3.2.13 on 2022-05-28 17:49

from django.db import migrations, models
import django.db.models.deletion
import orders.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('start_date', models.DateTimeField(validators=[orders.validators.validate_start_date], verbose_name='Дата начала срока эксплуатации')),
                ('phone', models.CharField(max_length=13, validators=[orders.validators.validate_phone], verbose_name='Телефон')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания срока эксплуатации')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('called', 'Заказ согласован'), ('in_process', 'Заказ отдан заказчику'), ('closed', 'Заказ закрыт')], max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductsToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_orders', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар к заказу',
                'verbose_name_plural': 'Товары к заказам',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.ProductsToOrder', to='products.Product', verbose_name='Товары'),
        ),
    ]
