# Generated by Django 3.2.13 on 2022-05-27 14:47

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.CharField(choices=[('text', 'Текст'), ('varchar', 'Короткий текст'), ('enum', 'Выборочный')], max_length=50, verbose_name='Тип данных')),
                ('name', models.CharField(help_text='Дружественное для пользователя', max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Уникальное название атрибута')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='EnumGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы выбора')),
            ],
            options={
                'verbose_name': 'Группа выбора',
                'verbose_name_plural': 'Группы выбора',
            },
        ),
        migrations.CreateModel(
            name='EnumValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('enum_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.enumgroup', verbose_name='Группа выбора')),
            ],
            options={
                'verbose_name': 'Значение группы выбора',
                'verbose_name_plural': 'Значения группы выбора',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('image', models.ImageField(max_length=255, upload_to=products.models.Product.upload_to, verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена в сутки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_varchar', models.CharField(blank=True, max_length=255, verbose_name='Значение')),
                ('value_text', models.TextField(blank=True, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('value_enum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enum_values', to='products.enumvalue', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='enum_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.enumgroup', verbose_name='Группа выбора'),
        ),
    ]
