# Generated by Django 3.2.13 on 2022-06-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_auto_20220602_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributegroup', verbose_name='Группа'),
        ),
    ]
