# Generated by Django 3.2.13 on 2022-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220602_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
