# Generated by Django 3.2.13 on 2022-05-28 17:49

from django.db import migrations, models
import studios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название студии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена в час')),
                ('image', models.ImageField(max_length=255, upload_to=studios.models.Studio.upload_to, verbose_name='Фотография')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
            },
        ),
    ]
