# Generated by Django 3.2.13 on 2022-05-28 17:49

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название новости')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(max_length=255, upload_to=news.models.New.upload_to, verbose_name='Фотография')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
